### ISSUE TITLE
System.InvalidCastException:

### ISSUE THREAD

**Issue by donalmc** [deepakkumar1984/XrmToolBoxPlugins#11]
Hi

When I try to run the the plugin against the lead entity, I get the below error message.

Thanks,
Donal

 
************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Microsoft.Crm.Sdk.Messages.AuditDetail' to type 'Microsoft.Crm.Sdk.Messages.AttributeAuditDetail'.
   at BDK.XrmToolBox.RecycleBin.PluginControl.<btnShowRecords_Click>b__11_0(BackgroundWorker w, DoWorkEventArgs ev)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

************** Loaded Assemblies **************

**Comment by deepakkumar1984** [comment]
Should be fixed by now. Please let me know if still having issues
