### ISSUE TITLE
Unhandled Exception Error when trying to see Deleted Records

### ISSUE THREAD

**Issue by KJP838** [deepakkumar1984/XrmToolBoxPlugins#28]
I am getting an error when using this through the XRMToolBox

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Microsoft.Crm.Sdk.Messages.AuditDetail' to type 'Microsoft.Crm.Sdk.Messages.AttributeAuditDetail'.
   at BDK.XrmToolBox.RecycleBin.PluginControl.<btnShowRecords_Click>b__11_0(BackgroundWorker w, DoWorkEventArgs ev)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by deepakkumar1984** [comment]
Which version of CRM you using?

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
