### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 

### ISSUE THREAD

**Issue by CloudpointSys** [deepakkumar1984/XrmToolBoxPlugins#55]
I get error when using XRM Recycle bin.

System.InvalidCastException: Unable to cast object of type 'Microsoft.Crm.Sdk.Messages.AuditDetail' to type 'Microsoft.Crm.Sdk.Messages.AttributeAuditDetail'.
   at BDK.XrmToolBox.RecycleBin.PluginControl.<btnShowRecords_Click>b__11_0(BackgroundWorker w, DoWorkEventArgs ev)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
